/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package repodepot;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scnr = new Scanner(System.in);

        System.out.println("________________________________________________________________");
        System.out.println("    /'\\      /'''''\\   /'''''\\   /'''''\\   |'''''''\\   |'''''\\  ");
        System.out.println("   /   \\    |  ____/  |  ____/  |  |'|  |  |  | |   |  | |'|  \\ ");
        System.out.println("  /=====\\   |  |      |  |      |  | |  |  |   _   /   | | |   |");
        System.out.println(" /       \\  |  ''''\\  |  ''''\\  |  |_|  |  |  | \\  \\   | |_|  / ");
        System.out.println("/         \\  \\_____/   \\_____/   \\_____/   |__|  \\__\\  |_____/  ");
        System.out.println("________________________________________________________________");
        System.out.println("");
        System.out.println("[1] Login");
        System.out.println("[2] Sign up");
        String log_or_sign = scnr.nextLine();
        if (log_or_sign == "1"){
            //bring to log in page
        } else if (log_or_sign == "2"){
            //bring to sign up page
        }
        home();
    }

    public static void home(){
        Scanner scnr = new Scanner(System.in);

        System.out.println("Welcome [USERNAME]");
        System.out.println("[1] Send Message");
        System.out.println("[2] See Users");
        System.out.println("[3] Rooms");
        System.out.println("[4] Check Messages");
        System.out.println("[5] Update Profile");
        String opt = scnr.nextLine();

        switch(opt){
            case "1":
                //send message
            break;
            case "2":
                //see users
            break;
            case "3":
                //rooms
            break;
            case "4":
                //check messages
            break;
            case "5":
                //update profile
            break;
        }
    }
}




/*String connectionString = "mongodb+srv://emCorey:test1234@cluster0.cwb4w.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0";
        try (MongoClient mongoClient = MongoClients.create(connectionString)) {
            MongoDatabase database = mongoClient.getDatabase("DolphinMangoCore");
            MongoCollection<Document> collection = database.getCollection("users");
            
            
        }*/
